# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    volumes:
      - ../../dist:/usr/share/nginx/html
    ports:
      - "80:8080"
      - "443:443"
